// Code generated by bpf2go; DO NOT EDIT.
//
// This file provides a manually written bpf2go-style loader.
// To regenerate automatically, run:
//   go generate ./...
// which invokes:
//   bpf2go -cc clang -target bpfel bpf bpf/flow.c

package main

import (
	"bytes"
	_ "embed"
	"fmt"

	"github.com/cilium/ebpf"
)

//go:embed bpf_bpfel.o
var bpfBin []byte

type flowObjects struct {
	Flows       *ebpf.Map `ebpf:"flows"`
	IPMeta      *ebpf.Map `ebpf:"ip_meta"`
	EnforceMode *ebpf.Map `ebpf:"enforce_mode"`
	Blocked     *ebpf.Map `ebpf:"blocked"`
	Events      *ebpf.Map `ebpf:"events"`
	BlockEvents *ebpf.Map `ebpf:"block_events"`

	HandleIngress *ebpf.Program `ebpf:"handle_ingress"`
	HandleEgress  *ebpf.Program `ebpf:"handle_egress"`
}

func loadFlowObjects() (*flowObjects, error) {
	spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(bpfBin))
	if err != nil {
		return nil, fmt.Errorf("load BPF spec: %w", err)
	}
	var obj flowObjects
	if err := spec.LoadAndAssign(&obj, nil); err != nil {
		return nil, fmt.Errorf("load and assign BPF objects: %w", err)
	}
	return &obj, nil
}

func (o *flowObjects) Close() {
	if o.Flows != nil       { _ = o.Flows.Close() }
	if o.IPMeta != nil      { _ = o.IPMeta.Close() }
	if o.EnforceMode != nil { _ = o.EnforceMode.Close() }
	if o.Blocked != nil     { _ = o.Blocked.Close() }
	if o.Events != nil      { _ = o.Events.Close() }
	if o.BlockEvents != nil { _ = o.BlockEvents.Close() }
	if o.HandleIngress != nil { _ = o.HandleIngress.Close() }
	if o.HandleEgress != nil  { _ = o.HandleEgress.Close() }
}

const (
	IPStateActive   uint8 = 1
	IPStateReleased uint8 = 2
)

type PodMetaValue struct {
	State        uint8
	Pad          [7]uint8
	UpdatedAtNs  uint64
	NameHash     uint64
}

type BlockedValue struct {
	Packets  uint64
	Bytes    uint64
	FirstTs  uint64
	LastTs   uint64
}

type BlockEvent struct {
	Saddr     uint32
	Daddr     uint32
	Sport     uint16
	Dport     uint16
	Proto     uint8
	Pad       [3]uint8
	Seq       uint32
	Ack       uint32
	TcpFlags  uint16
	Pad2      uint16
	TsNs      uint64
}
