process ddos-mitigator {
    run /usr/bin/python3 /path/to/ddos-mitigator/main.py;
    encoder json;
}

neighbor 192.168.1.2 {
    router-id 192.168.1.1;
    local-address 192.168.1.1;
    local-as 65001;
    peer-as 65000;

    api {
        processes [ddos-mitigator];
    }

    family {
        flow {
            ipv4 unicast;
        }
    }
}
