server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: config-center-server
  jackson:
    serialization:
      write-dates-as-timestamps: false

config-center:
  etcd:
    endpoints: http://localhost:2379
    prefix: /config-center
  grpc:
    host: 0.0.0.0
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
