agent {
    data_dir = "/opt/spire/.data/data"
    log_level = "INFO"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/tmp/spire-agent/public/api.sock"
    trust_bundle_path = "/opt/spire/.data/conf/agent/bootstrap.crt"
}

plugins {
    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/.data/data"
        }
    }
    NodeAttestor "join_token" {
        plugin_data {}
    }
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
